export const SHEET_IDS = {
  basicInfo: "12ldWoK9YamCXX3jik9CVxlX0mFFsjAhB_kB2DF1CMwQ",
  qualifications: "119frWoy-aKRnpw87xGComqtKUpL-lXUiL6YHBbZtiF4",
  teaching: "1YUeM1icAETCoslGzXRHPjEqZWspAaF7iWI8HJaPYu0g",
  courses: "1m_XUlCU7APvLYsgH6x2LbAEeqimcpCBNrEdgv5F_iKI",
  institutional: "1EUQyUtybxHN-CUj1pJT2k_gwZ4lvVkiIpNyEdYl8DbA",
  journalPublications: "1IIzO8YzmwAC4YWIT1kO3-xx4lo4_YDJ45rARba78h_g",
  conferencePublications: "10lsqxsn_y2NanvIl-2zoBuoTLjZRFq7yhh5cLnko_f4",
  researchProjects: "1Jp1uqLKgVgNcHDjBEVf3CNu1h7fMFT6pMxUPanPKjMc",
  patents: "1jeGxJDXm_KWfkJbMKLk6Xn3YkceSK6PnJIxHBh4lxHQ",
  fdp: "1RkctxPBPBM3DxICCXDluOuGfmIfei52TIiH4XTuUZr0",
  memberships: "1MJQYLoG7FBQpsjS_hILNTSHSzR7zxDqmcw6FDb33LKs",
  responsibilities: "1DJkGt0SpO38KpW-rY9k4Sh1AaWxj1QGCB2ZMFWvIv3w",
  mentoring: "1zX6Pmk-fw-ICbAzMygoOWRWtdbg-IhZByIqldzSduAc",
  declaration: "1TsIIbA3YOIYVqLPeHL4cXG7J0rYLK06Gig0j1pGCfkU",
  awards: "1rjGz0vMSO9oBGOZxaFLCSM8dgkro1nN_N61FjHa3_3E",
  extension: "144rPBy60JhQrZZ5uDm0C0Xo6_ul9D5d_pan0OG3qCrw",
  skills: "12kfOam0CIXJQS3J4Z2wzTGe4eqM66KpyIXZsPsBOjQk",
  onlineProfiles: "1QKEOb-4eRH2f5K0MFDC0Gmew17GGvxmbWamF8d1SwwY",
  contactMe: "1OpS_8bM3RUJUlu63Ei5ZvT1TJTuDLhMl5VPTl1jQcbU",
};

export const SECTION_TITLES: Record<keyof typeof SHEET_IDS, string> = {
  basicInfo: "Basic Information",
  qualifications: "Academic Qualifications",
  teaching: "Teaching Experience",
  courses: "Courses Taught",
  institutional: "Institutional Contributions",
  journalPublications: "Journal Publications",
  conferencePublications: "Conference Publications",
  researchProjects: "Research Projects",
  patents: "Patents & Innovations",
  fdp: "FDP & Certifications",
  memberships: "Professional Memberships",
  responsibilities: "Academic Responsibilities",
  mentoring: "Student Mentoring",
  declaration: "Declaration",
  awards: "Awards & Recognitions",
  extension: "Extension & Outreach",
  skills: "Technical Skills",
  onlineProfiles: "Connect",
  contactMe: "Contact Me",
};

export const CONTACT_FORM_URL = ""; // PASTE YOUR GOOGLE WEB APP URL HERE
